#!/bin/bash
set -eo pipefail
cd /home/bryce/mycelium
env DEV=AMD ALG2=1 ALG_FTYPES=8 ALG_DUP=1 ALG_HW=512 ALG_WIDE=1 ALG_TRUNK_LORA=1 ALG_LORA_R=4 ALG_LORA_SPAN=0123 ALG_LORA_PROJ=wod ALG_ROPE_OFF=0 ALG_TEST=.cache/algebra_nl_bigtest.jsonl ALG_TEST_NAME=bigtest RV_ID=R20 .venv/bin/python3 scripts/reader_vote_one.py >> .cache/rootvotes.log 2>&1
env DEV=AMD ALG2=1 ALG_FTYPES=8 ALG_DUP=1 ALG_HW=512 ALG_WIDE=1 ALG_TRUNK_LORA=1 ALG_LORA_R=32 ALG_LORA_SPAN=01 ALG_LORA_PROJ=wod ALG_ROPE_OFF=89 ALG_TEST=.cache/algebra_nl_bigtest.jsonl ALG_TEST_NAME=bigtest RV_ID=R15 .venv/bin/python3 scripts/reader_vote_one.py >> .cache/rootvotes.log 2>&1
env DEV=AMD ALG2=1 ALG_FTYPES=8 ALG_DUP=1 ALG_HW=512 ALG_WIDE=1 ALG_TRUNK_LORA=1 ALG_LORA_R=8 ALG_LORA_SPAN=0123 ALG_LORA_PROJ=wq ALG_ROPE_OFF=23 ALG_TEST=.cache/algebra_nl_bigtest.jsonl ALG_TEST_NAME=bigtest RV_ID=R17 .venv/bin/python3 scripts/reader_vote_one.py >> .cache/rootvotes.log 2>&1
env DEV=AMD ALG2=1 ALG_FTYPES=8 ALG_DUP=1 ALG_HW=512 ALG_WIDE=1 ALG_TRUNK_LORA=1 ALG_LORA_R=16 ALG_LORA_SPAN=01 ALG_LORA_PROJ=wod ALG_ROPE_OFF=0 ALG_TEST=.cache/algebra_nl_bigtest.jsonl ALG_TEST_NAME=bigtest RV_ID=R18 .venv/bin/python3 scripts/reader_vote_one.py >> .cache/rootvotes.log 2>&1
env DEV=AMD ALG2=1 ALG_FTYPES=8 ALG_DUP=1 ALG_HW=512 ALG_WIDE=1 ALG_TRUNK_LORA=1 ALG_LORA_R=32 ALG_LORA_SPAN=0123 ALG_LORA_PROJ=wod ALG_ROPE_OFF=0 ALG_TEST=.cache/algebra_nl_bigtest.jsonl ALG_TEST_NAME=bigtest RV_ID=R12 .venv/bin/python3 scripts/reader_vote_one.py >> .cache/rootvotes.log 2>&1
env DEV=AMD ALG2=1 ALG_FTYPES=8 ALG_DUP=1 ALG_HW=512 ALG_WIDE=1 ALG_TRUNK_LORA=1 ALG_LORA_R=8 ALG_LORA_SPAN=23 ALG_LORA_PROJ=wod ALG_ROPE_OFF=101 ALG_TEST=.cache/algebra_nl_bigtest.jsonl ALG_TEST_NAME=bigtest RV_ID=R06 .venv/bin/python3 scripts/reader_vote_one.py >> .cache/rootvotes.log 2>&1
env DEV=AMD ALG2=1 ALG_FTYPES=8 ALG_DUP=1 ALG_HW=512 ALG_WIDE=1 ALG_TRUNK_LORA=1 ALG_LORA_R=32 ALG_LORA_SPAN=0123 ALG_LORA_PROJ=all ALG_ROPE_OFF=53 ALG_TEST=.cache/algebra_nl_bigtest.jsonl ALG_TEST_NAME=bigtest RV_ID=R04 .venv/bin/python3 scripts/reader_vote_one.py >> .cache/rootvotes.log 2>&1
env DEV=AMD ALG2=1 ALG_FTYPES=8 ALG_DUP=1 ALG_HW=512 ALG_WIDE=1 ALG_TRUNK_LORA=1 ALG_LORA_R=4 ALG_LORA_SPAN=01 ALG_LORA_PROJ=all ALG_ROPE_OFF=29 ALG_NOTEBOOK=1 ALG_BREATH=3 ALG_TEST=.cache/algebra_nl_bigtest.jsonl ALG_TEST_NAME=bigtest RV_ID=R07 .venv/bin/python3 scripts/reader_vote_one.py >> .cache/rootvotes.log 2>&1
env DEV=AMD ALG2=1 ALG_FTYPES=8 ALG_DUP=1 ALG_HW=512 ALG_WIDE=1 ALG_TRUNK_LORA=1 ALG_LORA_R=16 ALG_LORA_SPAN=01 ALG_LORA_PROJ=wq ALG_ROPE_OFF=0 ALG_TEST=.cache/algebra_nl_bigtest.jsonl ALG_TEST_NAME=bigtest RV_ID=R05 .venv/bin/python3 scripts/reader_vote_one.py >> .cache/rootvotes.log 2>&1
env DEV=AMD ALG2=1 ALG_FTYPES=8 ALG_DUP=1 ALG_HW=512 ALG_WIDE=1 ALG_TRUNK_LORA=1 ALG_LORA_R=16 ALG_LORA_SPAN=0123 ALG_LORA_PROJ=wq ALG_ROPE_OFF=0 ALG_TEST=.cache/algebra_nl_bigtest.jsonl ALG_TEST_NAME=bigtest RV_ID=R14 .venv/bin/python3 scripts/reader_vote_one.py >> .cache/rootvotes.log 2>&1
env DEV=AMD ALG2=1 ALG_FTYPES=8 ALG_DUP=1 ALG_HW=512 ALG_WIDE=1 ALG_TRUNK_LORA=1 ALG_LORA_R=4 ALG_LORA_SPAN=23 ALG_LORA_PROJ=wod ALG_ROPE_OFF=0 ALG_TEST=.cache/algebra_nl_bigtest.jsonl ALG_TEST_NAME=bigtest RV_ID=R03 .venv/bin/python3 scripts/reader_vote_one.py >> .cache/rootvotes.log 2>&1
env DEV=AMD ALG2=1 ALG_FTYPES=8 ALG_DUP=1 ALG_HW=512 ALG_WIDE=1 ALG_TRUNK_LORA=1 ALG_LORA_R=16 ALG_LORA_SPAN=0123 ALG_LORA_PROJ=wod ALG_ROPE_OFF=71 ALG_TEST=.cache/algebra_nl_bigtest.jsonl ALG_TEST_NAME=bigtest RV_ID=R09 .venv/bin/python3 scripts/reader_vote_one.py >> .cache/rootvotes.log 2>&1
env DEV=AMD ALG2=1 ALG_FTYPES=8 ALG_DUP=1 ALG_HW=512 ALG_WIDE=1 ALG_TRUNK_LORA=1 ALG_LORA_R=4 ALG_LORA_SPAN=23 ALG_LORA_PROJ=wq ALG_ROPE_OFF=13 ALG_TEST=.cache/algebra_nl_bigtest.jsonl ALG_TEST_NAME=bigtest RV_ID=R11 .venv/bin/python3 scripts/reader_vote_one.py >> .cache/rootvotes.log 2>&1
env DEV=AMD ALG2=1 ALG_FTYPES=8 ALG_DUP=1 ALG_HW=512 ALG_WIDE=1 ALG_TRUNK_LORA=1 ALG_LORA_R=32 ALG_LORA_SPAN=23 ALG_LORA_PROJ=wq ALG_ROPE_OFF=61 ALG_NOTEBOOK=1 ALG_BREATH=3 ALG_TEST=.cache/algebra_nl_bigtest.jsonl ALG_TEST_NAME=bigtest RV_ID=R19 .venv/bin/python3 scripts/reader_vote_one.py >> .cache/rootvotes.log 2>&1
env DEV=AMD ALG2=1 ALG_FTYPES=8 ALG_DUP=1 ALG_HW=512 ALG_WIDE=1 ALG_TRUNK_LORA=1 ALG_LORA_R=8 ALG_LORA_SPAN=01 ALG_LORA_PROJ=all ALG_ROPE_OFF=0 ALG_TEST=.cache/algebra_nl_bigtest.jsonl ALG_TEST_NAME=bigtest RV_ID=R10 .venv/bin/python3 scripts/reader_vote_one.py >> .cache/rootvotes.log 2>&1
env DEV=AMD ALG2=1 ALG_FTYPES=8 ALG_DUP=1 ALG_HW=512 ALG_WIDE=1 ALG_TRUNK_LORA=1 ALG_LORA_R=16 ALG_LORA_SPAN=0123 ALG_LORA_PROJ=all ALG_ROPE_OFF=0 ALG_TEST=.cache/algebra_nl_bigtest.jsonl ALG_TEST_NAME=bigtest RV_ID=R01 .venv/bin/python3 scripts/reader_vote_one.py >> .cache/rootvotes.log 2>&1
