"""
LoRA Hooks for State-Conditioned LoRA in Llama Attention Layers.

This module provides infrastructure for applying and removing state-conditioned
LoRA modifications to Llama's attention projections (Q, K, V, O) through
forward hooks.

The LoRA modification formula:
    output = original_output + (x @ A * scales) @ B

Where:
    - A: Down-projection matrix (d_model, rank)
    - B: Up-projection matrix (rank, d_model)
    - scales: Per-batch, per-rank scaling factors (batch, rank)

The scales are generated by a hypernetwork from the state vector, allowing
the LoRA modifications to change on each thinking pass.

Usage:
    from src.lora_hooks import LoRAHookManager, apply_lora, remove_lora
    from src.state_conditioned_lora import StateConditionedLoRA

    lora_module = StateConditionedLoRA(...)
    state = torch.randn(1, 64)  # state on hypersphere

    # Apply LoRA hooks
    apply_lora(model.transformer, lora_module, state)

    # Forward pass (LoRA modifications active)
    outputs = model.transformer(input_ids=input_ids, ...)

    # Remove hooks after pass
    remove_lora(model.transformer)
"""

import torch
import torch.nn as nn
from typing import Dict, List, Tuple, Optional, Callable, Any
from functools import partial


class LoRAHookManager:
    """
    Manager for LoRA forward hooks on Llama attention layers.

    Handles registration and removal of hooks that modify the output of
    Q, K, V, O projections with state-conditioned LoRA.

    Attributes:
        handles: List of hook handles for cleanup
        model: Reference to the transformer model
        num_layers: Number of transformer layers (16 for Llama 3.2 1B)

    Example:
        manager = LoRAHookManager(model.transformer)
        manager.apply(lora_mods)
        # ... forward pass ...
        manager.remove()
    """

    PROJECTION_NAMES = ['q_proj', 'k_proj', 'v_proj', 'o_proj']

    def __init__(self, model: nn.Module):
        """
        Initialize the hook manager.

        Args:
            model: The transformer model (e.g., LlamaForCausalLM).
                   Expects layers at model.model.layers[i].self_attn
        """
        self.model = model
        self.handles: List[torch.utils.hooks.RemovableHandle] = []

        # Determine number of layers
        if hasattr(model, 'model') and hasattr(model.model, 'layers'):
            self.num_layers = len(model.model.layers)
        else:
            # Fallback: try to find layers directly
            self.num_layers = 16  # Default for Llama 3.2 1B

    def _get_attention_layer(self, layer_idx: int) -> nn.Module:
        """Get the self_attn module for a given layer index."""
        return self.model.model.layers[layer_idx].self_attn

    def _create_lora_hook(
        self,
        A: torch.Tensor,
        B: torch.Tensor,
        scales: torch.Tensor,
    ) -> Callable:
        """
        Create a forward hook that applies LoRA modification.

        The hook modifies output as:
            output = original_output + (x @ A * scales) @ B

        Args:
            A: Down-projection matrix (d_model, rank)
            B: Up-projection matrix (rank, d_model)
            scales: Per-batch scaling factors (batch, rank)

        Returns:
            Hook function compatible with register_forward_hook
        """
        def hook(
            module: nn.Module,
            input: Tuple[torch.Tensor, ...],
            output: torch.Tensor,
        ) -> torch.Tensor:
            # Get input tensor
            x = input[0]  # (batch, seq, d_model)

            # Compute LoRA output
            # (batch, seq, d_model) @ (d_model, rank) = (batch, seq, rank)
            lora_down = x @ A.to(x.dtype).to(x.device)

            # Scale by per-batch, per-rank factors
            # scales: (batch, rank) -> (batch, 1, rank) for broadcasting
            scaled = lora_down * scales.to(x.dtype).to(x.device).unsqueeze(1)

            # Up-project
            # (batch, seq, rank) @ (rank, d_model) = (batch, seq, d_model)
            lora_out = scaled @ B.to(x.dtype).to(x.device)

            return output + lora_out

        return hook

    def apply(self, lora_mods: Dict[int, Dict[str, Dict[str, torch.Tensor]]]) -> None:
        """
        Apply LoRA modifications to all attention layers.

        Args:
            lora_mods: Dictionary mapping layer_idx -> projection_name -> {A, B, scales}
                       Structure:
                       {
                           0: {
                               'q_proj': {'A': tensor, 'B': tensor, 'scales': tensor},
                               'k_proj': {...},
                               'v_proj': {...},
                               'o_proj': {...},
                           },
                           1: {...},
                           ...
                       }

        Raises:
            RuntimeError: If hooks are already applied (must remove first)
        """
        if self.handles:
            raise RuntimeError(
                "LoRA hooks already applied. Call remove() before applying again."
            )

        for layer_idx, layer_mods in lora_mods.items():
            attn = self._get_attention_layer(layer_idx)

            for proj_name, params in layer_mods.items():
                if proj_name not in self.PROJECTION_NAMES:
                    continue

                proj_module = getattr(attn, proj_name)

                A = params['A']       # (d_model, rank)
                B = params['B']       # (rank, d_model)
                scales = params['scales']  # (batch, rank)

                hook = self._create_lora_hook(A, B, scales)
                handle = proj_module.register_forward_hook(hook)
                self.handles.append(handle)

    def remove(self) -> None:
        """
        Remove all LoRA hooks.

        Safe to call even if no hooks are registered.
        """
        for handle in self.handles:
            handle.remove()
        self.handles.clear()

    def is_active(self) -> bool:
        """Check if LoRA hooks are currently applied."""
        return len(self.handles) > 0

    def __del__(self):
        """Cleanup hooks on deletion."""
        self.remove()


# Global hook manager reference (for module-level apply/remove functions)
_global_managers: Dict[int, LoRAHookManager] = {}


def apply_lora(
    model: nn.Module,
    lora_module: nn.Module,
    state: torch.Tensor,
) -> LoRAHookManager:
    """
    Apply state-conditioned LoRA to all 16 attention layers.

    This function:
    1. Computes LoRA modifications from state using lora_module
    2. Registers forward hooks on Q, K, V, O projections in each layer
    3. Returns a manager for later cleanup

    Args:
        model: The transformer model (LlamaForCausalLM).
               Layers expected at model.model.layers[i].self_attn
        lora_module: StateConditionedLoRA module that computes LoRA params from state
        state: State vector on hypersphere (batch, state_size)

    Returns:
        LoRAHookManager instance for this application

    Example:
        manager = apply_lora(model.transformer, lora_module, state)
        outputs = model.transformer(input_ids=input_ids)
        manager.remove()  # or use remove_lora(model.transformer)
    """
    # Create manager
    manager = LoRAHookManager(model)

    # Get LoRA modifications from state
    lora_mods = lora_module(state)

    # Apply hooks
    manager.apply(lora_mods)

    # Store in global registry for remove_lora()
    model_id = id(model)
    _global_managers[model_id] = manager

    return manager


def remove_lora(model: nn.Module) -> None:
    """
    Remove all LoRA hooks from a model.

    This function removes hooks that were applied via apply_lora().
    Safe to call even if no hooks are applied.

    Args:
        model: The transformer model that has LoRA hooks applied

    Example:
        apply_lora(model.transformer, lora_module, state)
        outputs = model.transformer(input_ids=input_ids)
        remove_lora(model.transformer)
    """
    model_id = id(model)

    if model_id in _global_managers:
        _global_managers[model_id].remove()
        del _global_managers[model_id]


def _test_lora_hooks():
    """
    Test LoRA hooks with a dummy model.

    This test verifies:
    1. Hooks can be registered and removed
    2. LoRA modification is applied correctly
    3. Output changes when LoRA is applied
    4. Output returns to normal when LoRA is removed
    """
    print("Testing LoRA Hooks...")
    print("=" * 60)

    # Create a minimal mock of Llama's attention structure
    class MockLinear(nn.Module):
        def __init__(self, in_features, out_features):
            super().__init__()
            self.linear = nn.Linear(in_features, out_features)

        def forward(self, x):
            return self.linear(x)

    class MockSelfAttn(nn.Module):
        def __init__(self, d_model):
            super().__init__()
            self.q_proj = MockLinear(d_model, d_model)
            self.k_proj = MockLinear(d_model, d_model)
            self.v_proj = MockLinear(d_model, d_model)
            self.o_proj = MockLinear(d_model, d_model)

    class MockLayer(nn.Module):
        def __init__(self, d_model):
            super().__init__()
            self.self_attn = MockSelfAttn(d_model)

    class MockLlama(nn.Module):
        def __init__(self, d_model=64, num_layers=2):
            super().__init__()
            self.model = nn.Module()
            self.model.layers = nn.ModuleList([
                MockLayer(d_model) for _ in range(num_layers)
            ])

    # Create mock model
    d_model = 64
    num_layers = 2
    rank = 4
    batch_size = 2
    seq_len = 10

    mock_model = MockLlama(d_model=d_model, num_layers=num_layers)

    print(f"Mock model: {num_layers} layers, d_model={d_model}, rank={rank}")

    # Create dummy LoRA modifications
    def create_dummy_lora_mods():
        """Create LoRA modifications matching StateConditionedLoRA output format."""
        lora_mods = {}
        proj_names = ['q_proj', 'k_proj', 'v_proj', 'o_proj']

        for layer_idx in range(num_layers):
            lora_mods[layer_idx] = {}
            for proj_name in proj_names:
                lora_mods[layer_idx][proj_name] = {
                    'A': torch.randn(d_model, rank) * 0.1,
                    'B': torch.randn(rank, d_model) * 0.1,
                    'scales': torch.randn(batch_size, rank).tanh(),
                }

        return lora_mods

    # Create a mock lora_module that returns pre-computed mods
    class MockLoRAModule(nn.Module):
        def __init__(self, lora_mods):
            super().__init__()
            self.lora_mods = lora_mods

        def forward(self, state):
            return self.lora_mods

    lora_mods = create_dummy_lora_mods()
    mock_lora_module = MockLoRAModule(lora_mods)

    # Test input
    x = torch.randn(batch_size, seq_len, d_model)
    state = torch.randn(batch_size, 64)

    # Get baseline output (no LoRA)
    print("\n1. Baseline output (no LoRA):")
    q_proj = mock_model.model.layers[0].self_attn.q_proj
    output_baseline = q_proj(x)
    print(f"   Shape: {output_baseline.shape}")
    print(f"   Mean: {output_baseline.mean().item():.6f}")

    # Apply LoRA
    print("\n2. Apply LoRA hooks:")
    manager = apply_lora(mock_model, mock_lora_module, state)
    print(f"   Hooks registered: {len(manager.handles)}")
    print(f"   Expected: {num_layers * 4}")  # 4 projections per layer
    assert len(manager.handles) == num_layers * 4, "Wrong number of hooks"
    print(f"   Manager is_active: {manager.is_active()}")

    # Get output with LoRA
    print("\n3. Output with LoRA:")
    output_with_lora = q_proj(x)
    print(f"   Shape: {output_with_lora.shape}")
    print(f"   Mean: {output_with_lora.mean().item():.6f}")

    # Verify LoRA changed the output
    diff = (output_with_lora - output_baseline).abs().mean().item()
    print(f"   Diff from baseline: {diff:.6f}")
    assert diff > 0, "LoRA should change output"
    print("   Output changed: OK")

    # Remove LoRA
    print("\n4. Remove LoRA hooks:")
    remove_lora(mock_model)
    print(f"   Manager is_active: {manager.is_active()}")
    assert not manager.is_active(), "Hooks should be removed"

    # Verify output returns to baseline
    print("\n5. Output after removing LoRA:")
    output_after_remove = q_proj(x)
    diff_after = (output_after_remove - output_baseline).abs().mean().item()
    print(f"   Diff from baseline: {diff_after:.6f}")
    assert diff_after < 1e-6, "Output should match baseline after removing LoRA"
    print("   Output matches baseline: OK")

    # Test LoRAHookManager directly
    print("\n6. Test LoRAHookManager directly:")
    manager2 = LoRAHookManager(mock_model)
    manager2.apply(lora_mods)
    print(f"   Hooks registered: {len(manager2.handles)}")

    output_with_manager = q_proj(x)
    diff_manager = (output_with_manager - output_baseline).abs().mean().item()
    print(f"   Diff from baseline: {diff_manager:.6f}")
    assert diff_manager > 0, "Manager-applied LoRA should change output"

    manager2.remove()
    print(f"   After remove, is_active: {manager2.is_active()}")
    assert not manager2.is_active(), "Hooks should be removed"

    # Test double-apply protection
    print("\n7. Test double-apply protection:")
    manager3 = LoRAHookManager(mock_model)
    manager3.apply(lora_mods)
    try:
        manager3.apply(lora_mods)
        print("   ERROR: Should have raised RuntimeError")
        assert False
    except RuntimeError as e:
        print(f"   Caught expected error: {e}")
    manager3.remove()

    print("\n" + "=" * 60)
    print("All LoRA hook tests passed!")
    print("=" * 60)


if __name__ == "__main__":
    _test_lora_hooks()
